### Get all classrooms
GET {{baseUrl}}/Classroom HTTP/1.1


### Get classroom by id
GET {{baseUrl}}/Classroom/1 HTTP/1.1


### Add classroom 
POST {{baseUrl}}/Classroom
content-type: application/json

{
    "name": "Aula 3",
    "seatsNumber": "20"
}


### Update classroom 
PUT {{baseUrl}}/Classroom
content-type: application/json

{
    "id": 4, 
    "name": "Aula 4",
    "seatsNumber": "25"
}


### Delete classroom 
DELETE {{baseUrl}}/Classroom/4